#!/usr/bin/env bash
# Build (if needed) and start YaC4e. Safe to re-run: it is the "apply current state" command.
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")"
ENV_FILE="./.env"

# First run generates real credentials. The application defaults are admin/admin and a
# well-known agent token, which must not be what gets exposed on the network.
if [[ ! -f "$ENV_FILE" ]]; then
  echo "No .env found, generating credentials..."
  secret() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-32}"; }
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by start.sh on $(date -Iseconds). Keep this file private.
YAC4E_PORT=8080

POSTGRES_DB=yac4e
POSTGRES_USER=yac4e
POSTGRES_PASSWORD=$(secret 32)

YAC4E_BASIC_USERNAME=admin
YAC4E_BASIC_PASSWORD=$(secret 24)

YAC4E_SEED_AGENT_TOKEN=$(secret 40)
EOF
  chmod 600 "$ENV_FILE"
  echo "Credentials written to $(pwd)/.env"
fi

REBUILD=0
[[ "${1:-}" == "--rebuild" ]] && REBUILD=1

if [[ $REBUILD -eq 1 ]]; then
  echo "Rebuilding image from source..."
  docker compose build --pull
fi

echo "Starting YaC4e..."
docker compose up -d --build

# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a
PORT="${YAC4E_PORT:-8080}"

printf 'Waiting for the application to become healthy'
for _ in $(seq 1 60); do
  status="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' yac4e-app 2>/dev/null || echo missing)"
  if [[ "$status" == "healthy" ]]; then
    echo
    echo "YaC4e is up."
    echo "  URL:      http://$(hostname -I 2>/dev/null | awk '{print $1}'):${PORT}"
    echo "  Username: ${YAC4E_BASIC_USERNAME}"
    echo "  Password: ${YAC4E_BASIC_PASSWORD}"
    echo "  Agent token (Bearer, /api/agent only): ${YAC4E_SEED_AGENT_TOKEN}"
    exit 0
  fi
  if [[ "$status" == "missing" ]]; then
    echo
    echo "The application container is not running. Recent logs:" >&2
    docker compose logs --tail 40 app >&2
    exit 1
  fi
  printf '.'
  sleep 2
done

echo
echo "Timed out waiting for a healthy status. Recent logs:" >&2
docker compose logs --tail 40 app >&2
exit 1
